version: '3.4'

networks: 
  gc-test:
    driver: bridge

services:
  gcbuild:
    image: test-cg
    ports:
    - "8080:8080"
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - gc-test

  postgres_db:    
    image: postgres:latest
    ports:
      - "3333:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testgc"
    networks:
      - gc-test